#!/bin/bash

 declare -a cydia 
 cydia=($CYDIA) 
  
 if [[ $1 == install || $1 == upgrade ]]; then 
     if [[ ${CYDIA+@} ]]; then 
         eval "echo 'finish:reboot' >&${cydia[0]}" 
     fi 
 fi 
 
if [[ $1 == upgrade ]]; then
	exit 0;
fi
